---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: reboot-archlinux
    image: archlinux/base
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: archlinux
